### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by juliohm** [jacobusmmsmit/TernaryPlots.jl#18]
This package is not registered and that makes it difficult to add as a dependency.

**Comment by jacobusmmsmit** [comment]
Currently being registered here https://github.com/JuliaRegistries/General/pull/45000.

**Comment by liuyxpp** [comment]
@jacobusmmsmit It seems the auto-merge process was blocked by your comment. Maybe you can remove your comment there to re-trigger the auto-merge bot. Thanks!
